export let utilidades= [
    { nome: 'a10',                    marca: 'Samsung',     preco: 1500.00,  cate:'smartphones',  imagem:'./Assets/smartphones/a10.png',id:'1',},
    { nome: 'iPhone 13 Pro Max',      marca: 'Apple' ,      preco: 1199.9,   cate:'smartphones',  imagem:'./Assets/smartphones/iphone13promax.png',id:'2',},
    { nome: 'Samsung Galaxy S21',     marca: 'Samsung',     preco: 1099.9,   cate:'smartphones',  imagem:'./Assets/smartphones/s21.png',id:'3',}, 
    { nome: 'Google Pixel 6 Pro',     marca:'Google',       preco: 899.99,   cate:'smartphones',  imagem:'./Assets/smartphones/pixel6pro.png',id:'4',},   
    { nome: 'OnePlus 9 Pro',          marca: 'OnePlus',     preco: 799.99,   cate:'smartphones',  imagem:'./Assets/smartphones/oneplus9pro.png',id:'5',},   
    { nome: 'Xiaomi Mi 11 Ultra',     marca:'Xiaomi',       preco: 899.99,   cate:'smartphones',  imagem:'./Assets/smartphones/mi11ultra.png',id:'6',},   
    { nome: 'Huawei P40 Pro+',        marca:'Huawei',       preco: 999.99,   cate:'smartphones',  imagem:'./Assets/smartphones/huaweip40proplus.png',id:'7',},   
    { nome: 'LG G8 ThinQ',            marca: 'LG',          preco: 599.99,   cate:'smartphones',  imagem:'./Assets/smartphones/lg-g8-thinq-2.png',id:'8',},
    { nome: 'Sony Xperia 1 III',      marca: 'Sony'  ,      preco: 1099.99,  cate:'smartphones',  imagem:'./Assets/smartphones/sony-xperia-1-iii-01.png',id:'9',},
    { nome: 'Motorola Edge+',         marca:'Motorola',     preco: 799.99,   cate:'smartphones',  imagem:'./Assets/smartphones/motorola-edge-plus-2023-1.png',id:'10',},
    { nome: 'Asus ROG Phone 5',       marca: 'Asus'  ,      preco: 899.99,   cate:'smartphones',  imagem:'./Assets/smartphones/asus-rog-phone-5-2.png',id:'11',},
    { nome: 'Realme GT',              marca:'Realme',      preco: 499.99,    cate:'smartphones',  imagem:'./Assets/smartphones/realme-gt-master-1.png',id:'12',},
    { nome: 'Oppo Find X3 Pro',       marca: 'Oppo'  ,      preco: 899.99,   cate:'smartphones',  imagem:'./Assets/smartphones/oppo-find-x3-pro-4.png',id:'13',},
    { nome: 'Vivo X60 Pro+',          marca: 'Vivo'  ,      preco: 699.99,   cate:'smartphones',  imagem:'./Assets/smartphones/vivo-x60-pro-plus-1.png',id:'14',},
    { nome: 'Nokia 9 PureView',       marca:'Nokia' ,      preco: 599.99,    cate:'smartphones',  imagem:'./Assets/smartphones/nokia-9-pureview-4.png',id:'15',},
    { nome: 'Lenovo Legion Phone 2', marca:'Lenovo',      preco: 799.99,     cate:'smartphones',  imagem:'./Assets/smartphones/lenovo-legion-2-pro-phone-duel2-3.png',id:'16',},
    { nome: 'ZTE Axon 30 Ultra',      marca:'ZTE'   ,      preco: 699.99,    cate:'smartphones',  imagem:'./Assets/smartphones/zte-axon-30-ultra-1.png',id:'17',},
    { nome: 'Xiaomi Redmi Note 10 ',   marca:'Xiaomi',      preco: 299.99,    cate:'smartphones',  imagem:'./Assets/smartphones/xiaomi-redmi-note10-11.png',id:'18',},
    { nome: 'OnePlus Nord N200 5',    marca:'OnePlus',     preco: 249.99,    cate:'smartphones',  imagem:'./Assets/smartphones/oneplus-nord-n200-5g-1.png',id:'19',},
    { nome: 'Motorola Moto G Pow021', marca:'Motorola',    preco: 199.99,    cate:'smartphones',  imagem:'./Assets/smartphones/motorola-moto-g9-power-2021-2.png',id:'20',},
    { nome: 'Google Pixel 5a',        marca:'Google',      preco: 449.99,    cate:'smartphones',  imagem:'./Assets/smartphones/google-pixel-5a-5g-00.png',id:'21',},
    { nome: 'Asus Zenfone 8',         marca: 'Asus'  ,      preco: 699.99,   cate:'smartphones',  imagem:'./Assets/smartphones/asus-zenfone-8-01.png',id:'22',},
    { nome: 'Samsung Galaxy A52',     marca:'Samsung',     preco: 349.99,    cate:'smartphones',  imagem:'./Assets/smartphones/samsung-galaxy-a52-4g-10.png',id:'23',},
    { nome: 'iPhone SE (2020)',       marca:'Apple' ,      preco: 399.99,    cate:'smartphones',  imagem:'./Assets/smartphones/apple-iphone-se-2020-2.png',id:'24',},  
    { nome: 'Sony Xperia 10 III',     marca: 'Sony'  ,      preco: 349.99,   cate:'smartphones',  imagem:'./Assets/smartphones/sony-xperia-10-iii-02.png',id:'25',},
    { nome: 'Xiaomi Poco X3 Pro',     marca:'Xiaomi',      preco: 299.99,    cate:'smartphones',  imagem:'./Assets/smartphones/xiaomi-poco-x3-pro.png',id:'26',},
    { nome: 'Realme Narzo 30 Pro',    marca: 'Realme',      preco: 249.99,   cate:'smartphones',  imagem:'./Assets/smartphones/realme-narzo-30-pro-3.png',id:'27',},
    { nome: 'Oppo Reno 5 Pro+',       marca: 'Oppo',      preco: 599.99,     cate:'smartphones',  imagem:'./Assets/smartphones/oppo-reno10-pro-plus-10.png',id:'28',},
    { nome: 'Vivo V21 5G',            marca: 'Vivo',      preco: 399.99,     cate:'smartphones',  imagem:'./Assets/smartphones/vivo-v21-5g-1.png',id:'29',},   
    { nome: 'Nokia 5.4',             marca: 'Nokia',      preco: 199.99,     cate:'smartphones',  imagem:'./Assets/smartphones/nokia-54-2020-1.png',id:'30',},  
    { nome: 'LG K92 5G',              marca: 'LG',      preco: 299.99,       cate:'smartphones',  imagem:'./Assets/smartphones/lg-k92-5g-1.png',id:'31',},
    { nome: 'Motorola Moto G Sty202', marca:'Motorola',    preco: 299.99,    cate:'smartphones',  imagem:'./Assets/smartphones/motorola-moto-g-stylus-5g-2023-1.png',id:'32',},
    { nome: 'Google Pixel 4a',        marca:'Google',      preco: 349.99,    cate:'smartphones',  imagem:'./Assets/smartphones/google-pixel-4a-1.png',id:'33',},
    { nome: 'Asus Zenfone 7 Pro',     marca: 'Asus',      preco: 599.99,     cate:'smartphones',  imagem:'./Assets/smartphones/asus-zenfone7-pro-zs670ks-zs671ks-2.png',id:'34',},
    { nome: 'Samsung Galaxy M51',     marca: 'Samsung',     preco: 349.9,    cate:'smartphones',  imagem:'./Assets/smartphones/samsung-galaxy-m51-3.png',id:'35',},
    { nome: 'iPhone 12 Mini',         marca: 'Apple',      preco: 699.99,    cate:'smartphones',  imagem:'./Assets/smartphones/apple-iphone-12-mini-r1.png',id:'36',},
    { nome: 'Sony Xperia 5 II',       marca: 'Sony',      preco: 799.99,     cate:'smartphones',  imagem:'./Assets/smartphones/sony-xperia-5-ii-5g-2.png',id:'37',},
    { nome: 'Xiaomi Redmi 9',         marca:'Xiaomi',      preco: 199.99,    cate:'smartphones',  imagem:'./Assets/smartphones/xiaomi-redmi-9-pink.png',id:'38',},
    { nome: 'Realme C25',             marca: 'Realme',      preco: 149.99,   cate:'smartphones',  imagem:'./Assets/smartphones/realme-c25-1.png',id:'39',},
    { nome: 'Oppo A74 5G',            marca: 'Oppo',      preco: 249.99,     cate:'smartphones',  imagem:'./Assets/smartphones/oppo-a74-5g-1.png',id:'40',},
    { nome: 'Vivo Y20',               marca: 'Vivo',      preco: 149.99,     cate:'smartphones',  imagem:'./Assets/smartphones/vivo-y20-.png',id:'41',},
    { nome: 'Nokia 2.4',              marca:'Nokia' ,      preco: 99.99 ,    cate:'smartphones',  imagem:'./Assets/smartphones/nokia-24-1.png',id:'42',},
    { nome: 'LG Velvet',            marca:'LG',      preco: 499.99,          cate:'smartphones',  imagem:'./Assets/smartphones/lg-velvet-4g-1.png',id:'43',},
    { nome: 'Motorola Moto E6 Pl',    marca: 'Motorola',    preco: 129.99,   cate:'smartphones',  imagem:'./Assets/smartphones/motorola-moto-e6-play-1.png',id:'44',},
    { nome: 'Google Pixel 3a',        marca:'Google',      preco: 399.99,    cate:'smartphones',  imagem:'./Assets/smartphones/google-pixel-3a-1.png',id:'45',},
    { nome: 'Asus ROG Phone 3',       marca:'Asus',      preco: 699.99,      cate:'smartphones',  imagem:'./Assets/smartphones/asus-rog-phone3-1.png',id:'46',},   
    { nome: 'Samsung Galaxy A32',     marca: 'Samsung',     preco: 299.99,   cate:'smartphones',  imagem:'./Assets/smartphones/samsung-galaxy-a32-4g-3.png',id:'47',},
    { nome: 'iPhone XR',              marca:'Apple',      preco: 599.99,     cate:'smartphones',  imagem:'./Assets/smartphones/apple-iphone-xr-5.png',id:'48',},
    { nome: 'Sony Xperia 10 II',      marca: 'Sony',      preco: 299.99,     cate:'smartphones',  imagem:'./Assets/smartphones/sony-xperia-10-ii-002.png',id:'49',},
    { nome: 'Xiaomi Mi 10 Lite',      marca: 'Xiaomi',      preco: 299.99,   cate:'smartphones',  imagem:'./Assets/smartphones/xiaomi-mi-10t-lite_1.png',id:'50',},


    { nome: 'Notebook ThinkPad X1 Carbon',      marca: 'Lenovo',          preco: 1299.99, cate:"informatica", imagem:'./Assets/informatica/notebook_thinkpad.png',id:'51',},  
    { nome: 'Monitor Curvo 32"',                marca: 'Samsung',         preco: 349.99 , cate:"informatica", imagem:'./Assets/informatica/monitor_curvo_34.jpg',id:'52',},
    { nome: 'Teclado sem Fio K780',             marca: 'Logitech',        preco: 59.99,    cate:"informatica", imagem:'./Assets/informatica/53.jpg',id:'53',},
    { nome: 'Mouse Gamer G502 Hero',            marca: 'Logitech',        preco: 79.99,    cate:"informatica", imagem:'./Assets/informatica/mouse_gamer_g502.png',id:'54',},
    { nome: 'Impressora Multifuncional',        marca: 'Epson',           preco: 199.99,  cate:"informatica", imagem:'./Assets/informatica/impressora.jpg',id:'55',}, 
    { nome: 'SSD NVMe 1TB                    ', marca: 'Western Digital', preco: 149.99  , cate:"informatica", imagem: './Assets/informatica/ssd1tb.png',id:'56',}, 
    { nome: 'Roteador Wi-Fi AX5400           ', marca: 'Asus           ', preco: 199.99  , cate:"informatica", imagem: './Assets/informatica/roteadorwifiax5400.png',id:'57',}, 
    { nome: 'Webcam 4K Pro                   ', marca: 'Logitech       ', preco:  129.99 , cate:"informatica", imagem: './Assets/informatica/webcam4kpro.png',id:'58',},  
    { nome: 'Caixa de Som Bluetooth Charge 4 ', marca: 'JBL            ', preco:  89.99  , cate:"informatica", imagem: './Assets/informatica/ciaxadesombluetoothcharger4.png',id:'59',},  
    { nome: 'Software de Edição de Vídeo     ', marca: 'Adobe          ', preco:   249.99, cate:"informatica", imagem: './Assets/img.png',id:'60',},   
    { nome: 'Tablet Galaxy Tab S7            ', marca: 'Samsung        ', preco:   599.99, cate:"informatica", imagem: './Assets/informatica/galaxytabs7.png',id:'61',},   
    { nome: 'Monitor Ultrawide 34"           ', marca: 'LG             ', preco:  499.99 , cate:"informatica", imagem: './Assets/informatica/monitorultrawide34.png',id:'62',},  
    { nome: 'Teclado Mecânico K95 RGB        ', marca: 'Corsair        ', preco:  179.99 , cate:"informatica", imagem: './Assets/informatica/tecladok95.png',id:'63',},  
    { nome: 'Mouse sem Fio MX Anywhere 3     ', marca: 'Logitech       ', preco:  69.99  , cate:"informatica", imagem: './Assets/informatica/mouse_anywhere.jpg',id:'64',},  
    { nome: 'Impressora a Laser Colorida     ', marca: 'Brother        ', preco: 299.99  , cate:"informatica", imagem: './Assets/informatica/impressora_Laser.jpg',id:'65',}, 
    { nome: 'SSD M.2 1TB                     ', marca: 'Crucial        ', preco: 109.99  , cate:"informatica", imagem: './Assets/informatica/ssd_crucial.jpg',id:'66',}, 
    { nome: 'Roteador Mesh Wi-Fi 6           ', marca: 'Netgear        ', preco:  179.99 , cate:"informatica", imagem: './Assets/informatica/67.jpg',id:'67',}, /*comeca */ 
    { nome: 'Webcam HD C922                  ', marca: 'Logitech       ', preco: 99.99   , cate:"informatica", imagem: './Assets/informatica/68.jpg',id:'68',}, 
    { nome: 'Caixa de Som Bluetooth Pulse 4  ', marca: 'JBL            ', preco:  79.99  , cate:"informatica", imagem: './Assets/informatica/69.jpg',id:'69',},  
    { nome: 'Echo Dot 5° geração     '        , marca: 'Amazon         ', preco:  386.10 , cate:"informatica", imagem: './Assets/informatica/70.jpg',id:'70',},  
    { nome: 'Tablet iPad Pro 12.9"           ', marca: 'Apple          ', preco:  999.99 , cate:"informatica", imagem: './Assets/informatica/71.jpg',id:'71',},  
    { nome: 'Monitor LED 27"                 ', marca: 'Acer           ', preco: 249.99  , cate:"informatica", imagem: './Assets/informatica/72.jpg',id:'72',}, 
    { nome: 'Teclado sem Fio K380            ', marca: 'Logitech       ', preco: 39.99   , cate:"informatica", imagem: './Assets/informatica/tecladok380.png',id:'73',}, 
    { nome: 'Mouse Ergonômico MX Vertical    ', marca: 'Logitech       ', preco: 89.99   , cate:"informatica", imagem: './Assets/informatica/74.jpg',id:'74',}, 
    { nome: 'Impressora Multifuncional Laser ', marca: 'Canon          ', preco:  249.99 , cate:"informatica", imagem: './Assets/informatica/75.jpg',id:'75',},  
    { nome: 'SSD Externo 1TB                 ', marca: 'SanDisk        ', preco:  129.99 , cate:"informatica", imagem: './Assets/informatica/76.jpg',id:'76',},  
    { nome: 'Roteador Wi-Fi AC1900           ', marca: 'Linksys        ', preco:  149.99 , cate:"informatica", imagem: './Assets/informatica/77.jpg',id:'77',},  
    { nome: 'Webcam Full HD Pro              ', marca: 'Microsoft      ', preco:  79.99  , cate:"informatica", imagem: './Assets/informatica/78.jpg',id:'78',},  
    { nome: 'Caixa de Som Bluetooth Flip 5   ', marca: 'JBL            ', preco:  69.99  , cate:"informatica", imagem: './Assets/informatica/79.jpg',id:'79',},  
    { nome: 'Software de Design Gráfico      ', marca: 'Adobe          ', preco:  299.99 , cate:"informatica", imagem: './Assets/informatica/80.jpg',id:'80',},  
    { nome: 'Notebook MacBook Pro 13"        ', marca: 'Apple          ', preco:  1299.99, cate:"informatica", imagem: './Assets/informatica/81.jpg',id:'81',},  
    { nome: 'Monitor Curvo 27"               ', marca: 'Dell           ', preco:  299.99 , cate:"informatica", imagem: './Assets/informatica/82.jpg',id:'82',},  
    { nome: 'Teclado Mecânico Alloy FPS      ', marca: 'HyperX         ', preco:  99.99  , cate:"informatica", imagem: './Assets/informatica/83.jpg',id:'83',},  
    { nome: 'Mouse sem Fio G305              ', marca: 'Logitech       ', preco:  49.99  , cate:"informatica", imagem: './Assets/informatica/84.jpg',id:'84',},  
    { nome: 'Impressora Laser Monocromática  ', marca: 'Samsung        ', preco:  149.99 , cate:"informatica", imagem: './Assets/informatica/85.jpg',id:'85',},  
    { nome: 'SSD NVMe 2TB                    ', marca: 'Kingston       ', preco:  249.99 , cate:"informatica", imagem: './Assets/informatica/86.jpg',id:'86',},  
    { nome: 'Roteador Mesh Wi-Fi 6E          ', marca: 'Asus           ', preco:   299.99, cate:"informatica", imagem: './Assets/informatica/87.jpg',id:'87',},   
    { nome: 'Webcam 1080p HD                 ', marca: 'Logitech       ', preco: 59.99   , cate:"informatica", imagem: './Assets/informatica/88.jpg',id:'88',}, 
    { nome: 'Caixa de Som Bluetooth Xtreme 3 ', marca: 'JBL            ', preco:   129.99, cate:"informatica", imagem: './Assets/informatica/89.jpg',id:'89',},   
    { nome: 'Software de Segurança           ', marca: 'Norton       ' , preco:  49.99  , cate:"informatica", imagem: './Assets/informatica/90.jpg',id:'90',} ,  
    { nome: 'TV Smart LED 55" 4K',       marca: 'Samsung',      preco: 799.99 , id:'91',  cate:'TV', imagem:'./Assets/tvsmart/tvsamsung4k55.png',},  
    { nome: 'TV OLED 65" 4K',            marca: 'LG',           preco: 1499.99, id:'92',  cate:'TV', imagem:'./Assets/tvsmart/tvqledlg654k.png',},  
    { nome: 'TV QLED 75" 8K',            marca: 'Sony',         preco: 2999.99, id:'93',  cate:'TV', imagem:'./Assets/tvsmart/tvsonyqled754k.png',},  
    { nome: 'TV Smart LED 50" Full HD',  marca: 'Panasonic',    preco: 499.99 , id:'94',  cate:'TV', imagem:'./Assets/tvsmart/tvsmartled50fullhdpanasonic.png',},  
    { nome: 'TV OLED 55" 4K',            marca: 'Philips',      preco: 999.99 , id:'95',  cate:'TV', imagem:'./Assets/tvsmart/tvoled554kfullhdphilips.png',},  
    { nome: 'TV Smart LED 43" Full HD',  marca: 'Samsung',      preco: 399.99 , id:'96',  cate:'TV', imagem:'./Assets/tvsmart/tvsmartled43fullhdsamsung.png',},  
    { nome: 'TV QLED 65" 4K',            marca: 'LG',           preco: 1099.99, id:'97',  cate:'TV', imagem:'./Assets/tvsmart/tvqled654klg.png',},  
    { nome: 'TV Smart LED 32" HD',       marca: 'Sony',         preco: 249.99 , id:'98',  cate:'TV', imagem:'./Assets/tvsmart/98.png',},  
    { nome: 'TV OLED 48" 4K',            marca: 'Panasonic',    preco: 799.99 , id:'99',  cate:'TV', imagem:'./Assets/tvsmart/99.png',},  
    { nome: 'TV Smart LED 65" 4K',       marca: 'Philips',      preco: 899.99 , id:'100', cate:'TV', imagem:'./Assets/tvsmart/100.png',},  
    { nome: 'TV Smart LED 60" 4K' ,      marca: 'Samsung' ,     preco: 899.99 , id:'101', cate:'TV', imagem:'./Assets/tvsmart/101.png',},
    { nome: 'TV OLED 77" 8K' ,           marca: 'LG' ,          preco: 3999.99, id:'102', cate:'TV', imagem:'./Assets/tvsmart/102.png',},
    { nome: 'TV QLED 55" 4K' ,           marca: 'Sony' ,        preco: 1199.99, id:'103', cate:'TV', imagem:'./Assets/tvsmart/103.png',},
    { nome: 'TV Smart LED 55" 4K' ,      marca: 'Panasonic' ,   preco: 699.99 , id:'104', cate:'TV', imagem:'./Assets/tvsmart/104.png',},
    { nome: 'TV OLED 65" 4K' ,           marca: 'Philips' ,     preco: 1499.99, id:'105', cate:'TV', imagem:'./Assets/tvsmart/105.png',},
    { nome: 'TV Smart LED 48" Full HD' , marca: 'Samsung' ,     preco: 549.99 , id:'106', cate:'TV', imagem:'./Assets/tvsmart/106.png',},
    { nome: 'TV QLED 75" 4K' ,           marca: 'LG' ,          preco: 1999.99, id:'107', cate:'TV', imagem:'./Assets/tvsmart/107.png',},
    { nome: 'TV Smart LED 40" Full HD' , marca: 'Sony' ,        preco: 349.99 , id:'108', cate:'TV', imagem:'./Assets/tvsmart/108.png',},
    { nome: 'TV OLED 55" 8K' ,           marca: 'Panasonic' ,   preco: 2499.99, id:'109', cate:'TV', imagem:'./Assets/tvsmart/109.png',},
    { nome: 'TV Smart LED 75" 4K' ,      marca: 'Philips' ,     preco: 1799.99, id:'110', cate:'TV', imagem:'./Assets/tvsmart/110.png',},


    { nome: 'Geladeira Frost-Free   ',               marca: 'Brastemp  ',  preco: 1499.99,  id: '111', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/geladeirabrastemp.png', },
    { nome: 'Máquina de Lavar Roupa ',               marca: 'Electrolux',  preco: 799.99 ,  id: '112', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/maquinadelavarelectrolux.png', },
    { nome: 'Forno de Micro-ondas   ',               marca: 'Panasonic ',  preco: 149.99 ,  id: '113', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/microondaspanasonic.png', },
    { nome: 'Fogão a Gás            ',               marca: 'Bosch     ',  preco: 499.99 ,  id: '114', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/fogao.png', },
    { nome: 'Máquina de Café        ',               marca: 'Philips   ',  preco: 89.99  ,  id: '115', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/maquinadecafephilips.png', },
    { nome: 'Lava-Louças Compacta   ',               marca: 'Samsung   ',  preco: 699.99 ,  id: '116', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/lavaloucasamsung.png', },
    { nome: 'Aspirador de Pó        ',               marca: 'Dyson     ',  preco: 399.99 ,  id: '117', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/aspiradordepodyson.png', },
    { nome: 'Liquidificador         ',               marca: ' Oster    ',  preco:  49.99 ,  id: '118', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Fritadeira Air Fryer   ',               marca: 'Cuisinart ',  preco: 129.99 ,  id: '119', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Ferro de Passar a Vapor',               marca: 'Rowenta   ',  preco: 69.99  ,  id: '120', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Geladeira Side-by-Side'  ,              marca: 'LG        ',  preco: 2499.99,  id: '121', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Máquina de Lavar e Secar',              marca: 'Whirlpool ',  preco: 1299.99,  id: '122', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Forno Elétrico Embutido' ,              marca: 'Electrolux',  preco: 899.99 ,  id: '123', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Fogão de Indução'        ,              marca: 'Samsung   ',  preco: 799.99 ,  id: '124', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Cafeteira Programável'   ,              marca: 'Breville  ',  preco: 119.99 ,  id: '125', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Lava-Louças de Bancada'  ,              marca: 'Siemens   ',  preco: 499.99 ,  id: '126', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Aspirador Robô Inteligente',            marca: 'iRobot'  ,    preco: 349.99,   id: '127', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', }, 
    { nome: 'Liquidificador Multifuncional',         marca: 'Ninja',       preco: 79.99,    id: '128', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Air Fryer de Grande Capacidade',        marca: 'Chefman' ,    preco: 169.99 ,  id: '129', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Ferro de Passar a Vapor com Base',      marca: 'Philips',     preco: 49.99,    id: '130', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Freezer Vertical',                      marca: 'Electrolux' , preco: 799.99,   id: '131', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Máquina de Lavar Louça Integrada',      marca: 'Bosch'  ,     preco: 899.99,   id: '132', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Micro-ondas com Grill',                 marca: 'Sharp' ,      preco: 149.99,   id: '133', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Fogão a Gás com Forno Duplo',           marca: 'GE' ,         preco: 999.99,   id: '134', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Lava-Louças Compacta com WiFi',         marca: 'Whirlpool',   preco: 699.99,   id: '135', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Robô Aspirador de Pó com Mapeamento',   marca: 'Ecovacs',     preco: 349.99,   id: '136', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', }, 
    { nome: 'Liquidificador de Alta Potência',       marca: 'Vitamix' ,    preco: 299.99,   id: '137', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Air Fryer com Tela Digital' ,           marca: 'T-fal',       preco: 109.99,   id: '138', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
    { nome: 'Ferro de Passar a Vapor com Função',    marca: 'Tefal',       preco: 59.99 ,   id: '139', cate:'eletrodomestico', imagem:'./Assets/eletrodomestico/.png', },
 ]
console.table(utilidades)
 export function salvarLocalStorage(chave, informacao){
    localStorage.setItem(chave, JSON.stringify(informacao))
  }
  
  export function lerLocalStorage(chave){
    return JSON.parse(localStorage.getItem(chave))
  }

  export const idsProdutosCarrinho =  lerLocalStorage('carrinho') ?? {};


